style(pleasew): Fix indentation to follow rest of repo

diff --git a/pleasew b/pleasew
--- a/pleasew
+++ b/pleasew
@@ -15,12 +15,12 @@ DEFAULT_URL_BASE='https://get.please.build'
 OS="$(uname)"
 
 if [ "${OS}" = 'Darwin' ]; then
-   # switch between mac amd64/arm64
-   ARCH="$(uname -m)"
+    # switch between mac amd64/arm64
+    ARCH="$(uname -m)"
 else
-   # default to amd64 on other operating systems
-   # because we only build intel binaries
-   ARCH='amd64'
+    # default to amd64 on other operating systems
+    # because we only build intel binaries
+    ARCH='amd64'
 fi
 
 # Check `PLZ_CONFIG_PROFILE` or fall back to arguments for a profile.
@@ -42,37 +42,37 @@ EOS
 )"
 
 read_config() {
-   printf "%s" "${CONFIGS}" | xargs grep -i "${1}" 2>/dev/null | head -n 1
+    printf "%s" "${CONFIGS}" | xargs grep -i "${1}" 2>/dev/null | head -n 1
 }
 
 # We might already have it downloaded...
 LOCATION="$(read_config '^location' | cut -d '=' -f 2 | tr -d ' ')"
 
 if [ "${LOCATION:+x}" != "x" ]; then
-   if [ "${HOME:+x}" != "x" ]; then
-      # shellcheck disable=2016
-      printf >&2 '%b$HOME not set, not sure where to look for Please.%b\n' "${RED}" "${RESET}"
-      exit 1
-   fi
+    if [ "${HOME:+x}" != "x" ]; then
+        # shellcheck disable=2016
+        printf >&2 '%b$HOME not set, not sure where to look for Please.%b\n' "${RED}" "${RESET}"
+        exit 1
+    fi
 
-   LOCATION="${HOME}/.please"
+    LOCATION="${HOME}/.please"
 else
-   # It can contain a literal ~, need to explicitly handle that.
-   LOCATION="$(echo "${LOCATION}" | sed "s|~|${HOME}|")"
+    # It can contain a literal ~, need to explicitly handle that.
+    LOCATION="$(echo "${LOCATION}" | sed "s|~|${HOME}|")"
 fi
 
 # If this exists at any version, let it handle any update.
 TARGET="${LOCATION}/please"
 
 if [ -f "${TARGET}" ]; then
-   # shellcheck disable=2086
-   exec "${TARGET}" ${PLZ_ARGS:-} "${@}"
+    # shellcheck disable=2086
+    exec "${TARGET}" ${PLZ_ARGS:-} "${@}"
 fi
 
 URL_BASE="$(read_config '^downloadlocation' | cut -d '=' -f 2 | tr -d ' ')"
 
 if [ -z "${URL_BASE}" ]; then
-   URL_BASE="${DEFAULT_URL_BASE}"
+    URL_BASE="${DEFAULT_URL_BASE}"
 fi
 
 URL_BASE="${URL_BASE%/}"
@@ -83,21 +83,21 @@ VERSION="$(echo "${VERSION}" | tr -d ' ')" # Remove all spaces
 VERSION="${VERSION#>=}"                    # Strip any initial >=
 
 if [ -z "${VERSION}" ]; then
-   printf >&2 "%bCan't determine version, will use latest.%b\n" "${YELLOW}" "${RESET}"
-   VERSION=$(curl -fsSL "${URL_BASE}"/latest_version)
+  	 printf >&2 "%bCan't determine version, will use latest.%b\n" "${YELLOW}" "${RESET}"
+  	 VERSION=$(curl -fsSL "${URL_BASE}"/latest_version)
 fi
 
 # Find the os / arch to download. You can do this quite nicely with go env
 # but we use this script on machines that don't necessarily have Go itself.
 if [ "${OS}" = 'Linux' ]; then
-   GOOS='linux'
+    GOOS='linux'
 elif [ "${OS}" = 'Darwin' ]; then
-   GOOS='darwin'
+    GOOS='darwin'
 elif [ "${OS}" = 'FreeBSD' ]; then
-   GOOS='freebsd'
+    GOOS='freebsd'
 else
-   printf >&2 '%bUnknown operating system %s%b\n' "${RED}" "${OS}" "${RESET}"
-   exit 1
+    printf >&2 '%bUnknown operating system %s%b\n' "${RED}" "${OS}" "${RESET}"
+    exit 1
 fi
 
 PLEASE_URL="${URL_BASE}/${GOOS}_${ARCH}/${VERSION}/please_${VERSION}.tar.xz"
@@ -105,7 +105,7 @@ DIR="${LOCATION}/${VERSION}"
 
 # Potentially we could reuse this but it's easier not to really.
 if [ ! -d "${DIR}" ]; then
-   rm -Rf "${DIR}"
+    rm -Rf "${DIR}"
 fi
 
 printf >&2 '%bDownloading Please %s to %s...%b\n' "${GREEN}" "${VERSION}" "${DIR}" "${RESET}"
@@ -114,7 +114,7 @@ curl -fsSL "${PLEASE_URL}" | tar -xJpf- --strip-components=1 -C "${DIR}"
 
 # Link it all back up a dir
 for x in "${DIR}"/*; do
-   ln -sf "${x}" "${LOCATION}"
+    ln -sf "${x}" "${LOCATION}"
 done
 
 printf >&2 '%bShould be good to go now, running plz...%b\n' "${GREEN}" "${RESET}"
