Echo stuff on stderr instead of stdout

diff --git a/pleasew b/pleasew
--- a/pleasew
+++ b/pleasew
@@ -11,7 +11,7 @@ DEFAULT_URL_BASE="https://get.please.build"
 LOCATION=`grep -i "^location" .plzconfig 2>/dev/null | cut -d '=' -f 2 | tr -d ' '`
 if [ -z "$LOCATION" ]; then
     if [ -z "$HOME" ]; then
-	    echo -e "${RED}\$HOME not set, not sure where to look for Please.${RESET}"
+	    echo -e >&2 "${RED}\$HOME not set, not sure where to look for Please.${RESET}"
 	    exit 1
     fi
     LOCATION="${HOME}/.please"
@@ -36,7 +36,7 @@ VERSION="${VERSION#*=}"    # Strip until after first =
 VERSION="${VERSION/ /}"    # Remove all spaces
 VERSION="${VERSION#>=}"    # Strip any initial >=
 if [ -z "$VERSION" ]; then
-    echo -e "${YELLOW}Can't determine version, will use latest.${RESET}"
+    echo -e >&2 "${YELLOW}Can't determine version, will use latest.${RESET}"
     VERSION=`curl -fsSL ${URL_BASE}/latest_version`
 fi
 
@@ -48,7 +48,7 @@ if [ "$OS" = "Linux" ]; then
 elif [ "$OS" = "Darwin" ]; then
     GOOS="darwin"
 else
-    echo -e "${RED}Unknown operating system $OS${RESET}"
+    echo -e >&2 "${RED}Unknown operating system $OS${RESET}"
     exit 1
 fi
 # Don't have any builds other than amd64 at the moment.
@@ -60,7 +60,7 @@ DIR="${LOCATION}/${VERSION}"
 if [ ! -d "$DIR" ]; then
     rm -rf "$DIR"
 fi
-echo -e "${GREEN}Downloading Please ${VERSION} to ${DIR}...${RESET}"
+echo -e >&2 "${GREEN}Downloading Please ${VERSION} to ${DIR}...${RESET}"
 mkdir -p "$DIR"
 curl -fsSL "${PLEASE_URL}" | tar -xJpf- --strip-components=1 -C "$DIR"
 # Link it all back up a dir
@@ -68,5 +68,5 @@ for x in `ls "$DIR"`; do
     ln -sf "${DIR}/${x}" "$LOCATION"
 done
 ln -sf "${DIR}/please" "${LOCATION}/plz"
-echo -e "${GREEN}Should be good to go now, running plz...${RESET}"
+echo -e >&2 "${GREEN}Should be good to go now, running plz...${RESET}"
 exec "$TARGET" "$@"
